namespace RMV.Awesome.Model
{
    public class DesignTimeViewModel
    {
        public DesignTimeViewModel()
        {
            Items = new System.Collections.ObjectModel.ObservableCollection<Branch>();
            Items.Add(new Branch() { Title = "Attleboro", Address = "75 Park Street", Latitude = 41.943778, Longitude = -71.279825, Town = "Attleboro", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/f/f1/Old_Attleboro%2C_MA%2C_post_office.jpg" });
            Items.Add(new Branch() { Title = "Boston", Address = "630 Washington Street", Latitude = 42.352181, Longitude = -71.062456, Town = "Washington", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/9/94/USA-Massachusetts_State_House0.jpg/640px-USA-Massachusetts_State_House0.jpg" });
            Items.Add(new Branch() { Title = "Braintree", Address = "10 Plain Street", Latitude = 42.196212, Longitude = -71.003572, Town = "Braintree", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Braintree_Old_Library.jpg/640px-Braintree_Old_Library.jpg" });
            Items.Add(new Branch() { Title = "Brockton", Address = "490 Forest Ave", Latitude = 42.070619, Longitude = -71.041389, Town = "Brockton", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/8/85/BrocktonCityHall.jpg/592px-BrocktonCityHall.jpg" });
            Items.Add(new Branch() { Title = "Chicopee", Address = "1011 Chicopee Street", Latitude = 42.191904, Longitude = -72.600594, Town = "Chicopee", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/City_Hall%2C_Chicopee_MA.jpg/640px-City_Hall%2C_Chicopee_MA.jpg" });
            Items.Add(new Branch() { Title = "Danvers", Address = "100 Independence Way", Latitude = 42.55290641370957, Longitude = -70.93985795974731, Town = "Danvers", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/6/63/North_end_of_MA_Route_35_entering_Danvers%2C_MA.jpg/512px-North_end_of_MA_Route_35_entering_Danvers%2C_MA.jpg" });
            Items.Add(new Branch() { Title = "Easthampton", Address = "116 Pleasant St", Latitude = 42.272979, Longitude = -72.663482, Town = "East Hampton", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Mount_Tom_Easthampton_MA.JPG/320px-Mount_Tom_Easthampton_MA.JPG" });
            Items.Add(new Branch() { Title = "Fall River", Address = "203 Plymouth Avenue", Latitude = 41.697317, Longitude = -71.149106, Town = "Fall River", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/2/21/Downtown_Fall_River.jpg" });
            Items.Add(new Branch() { Title = "Greenfield", Address = "18 Miner Street", Latitude = 42.585972, Longitude = -72.619682, Town = "Greenfield", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Greenfield_Town_Hall.jpg/411px-Greenfield_Town_Hall.jpg" });
            Items.Add(new Branch() { Title = "Haverhill", Address = "4 Summer Street", Latitude = 42.777554, Longitude = -71.077176, Town = "Haverhill", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Tattersall_Farm%2C_Haverhill_MA.jpg/640px-Tattersall_Farm%2C_Haverhill_MA.jpg" });
            Items.Add(new Branch() { Title = "Lawrence", Address = "73 Winthrop Avenue", Latitude = 42.689929, Longitude = -71.149626, Town = "Lawrence", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/e/ee/Ayer_Mill_View.jpg" });
            Items.Add(new Branch() { Title = "Leominster", Address = "80 Erdman Way", Latitude = 42.547593, Longitude = -71.757933, Town = "Leominster", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/a/a0/Monument_Square_Leominster.jpg" });
            Items.Add(new Branch() { Title = "Lowell", Address = "  77 Middlesex Street", Latitude = 42.641479, Longitude = -71.310108, Town = "Lowell", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Front_of_boott_mill.jpg/320px-Front_of_boott_mill.jpg" });
            Items.Add(new Branch() { Title = "Martha's Vineyard", Address = "11 A Street", Latitude = 41.391582, Longitude = -70.603321, Town = "Marthas Vineyard", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Martha%27s_Vineyard_Cottages.jpg/640px-Martha%27s_Vineyard_Cottages.jpg" });
            Items.Add(new Branch() { Title = "Milford", Address = "14 Beach Street", Latitude = 42.142346, Longitude = -71.512389, Town = "Milford", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Milford_Town_Hall%2C_MA.jpg/320px-Milford_Town_Hall%2C_MA.jpg" });
            Items.Add(new Branch() { Title = "Nantucket", Address = "Broad Street", Latitude = 41.28554, Longitude = -70.097874, Town = "Nantucket", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Brant_Point_Light_-_Nantucket_MA.jpg/576px-Brant_Point_Light_-_Nantucket_MA.jpg" });
            Items.Add(new Branch() { Title = "Natick", Address = "Massachusetts Turnpike Natick Eastbound Service Center", Latitude = 42.311156, Longitude = -71.364892, Town = "Natick", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Fast_lane_sign.jpg/640px-Fast_lane_sign.jpg" });
            Items.Add(new Branch() { Title = "New Bedford", Address = "278 Union Street", Latitude = 41.633748, Longitude = -70.929116, Town = "New Bedford", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Downtown_New_Bedford_MA.jpg/640px-Downtown_New_Bedford_MA.jpg" });
            Items.Add(new Branch() { Title = "North Adams", Address = "33 Main Street", Latitude = 42.69956, Longitude = -73.113883, Town = "N Adams", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/MassMoCa.jpg/640px-MassMoCa.jpg" });
            Items.Add(new Branch() { Title = "Pittsfield", Address = "333 East Street", Latitude = 42.447641, Longitude = -73.247607, Town = "Pittsfield", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Park_Square%2C_Pittsfield_MA.jpg/640px-Park_Square%2C_Pittsfield_MA.jpg" });
            Items.Add(new Branch() { Title = "Plymouth", Address = "40 Industrial Park Road", Latitude = 41.960272, Longitude = -70.700532, Town = "Plymouth", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Mayflower_II.jpg/600px-Mayflower_II.jpg" });
            Items.Add(new Branch() { Title = "Revere", Address = "9 Everett Street", Latitude = 42.409733, Longitude = -71.00108, Town = "Revere", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Paul_Revere_Statue_by_Cyrus_E._Dallin%2C_North_End%2C_Boston%2C_MA.JPG/576px-Paul_Revere_Statue_by_Cyrus_E._Dallin%2C_North_End%2C_Boston%2C_MA.JPG" });
            Items.Add(new Branch() { Title = "Roslindale", Address = "8 Cummins Highway", Latitude = 42.286383, Longitude = -71.127759, Town = "Roslindale", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/SacredHeartRoslindale_PWFord2.jpg/566px-SacredHeartRoslindale_PWFord2.jpg" });
            Items.Add(new Branch() { Title = "South Yarmouth", Address = "1084 Route 28", Latitude = 41.661432, Longitude = -70.202079, Town = "Yarmouth", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Bass_River%2C_South_Yarmouth_MA.jpg/640px-Bass_River%2C_South_Yarmouth_MA.jpg" });
            Items.Add(new Branch() { Title = "Southbridge", Address = "6 Larochelle Way", Latitude = 42.07704, Longitude = -72.033211, Town = "Southbridge", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Southbridge_Town_Hall.jpg/358px-Southbridge_Town_Hall.jpg" });
            Items.Add(new Branch() { Title = "Springfield", Address = "165 Liberty Street", Latitude = 42.108267, Longitude = -72.593402, Town = "Springfield", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Avenue_of_States%2C_The_Big_E%2C_West_Springfield_MA.jpg/320px-Avenue_of_States%2C_The_Big_E%2C_West_Springfield_MA.jpg" });
            Items.Add(new Branch() { Title = "Taunton", Address = "1 Washington Street", Latitude = 41.902468, Longitude = -71.099749, Town = "Taunton", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/4/48/Taunton_Green_Statue.jpg" });
            Items.Add(new Branch() { Title = "Watertown", Address = "550 Arsenal Street", Latitude = 42.363053, Longitude = -71.158113, Town = "Watertown", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Main_Street_Watertown_MA_2.jpg/320px-Main_Street_Watertown_MA_2.jpg" });
            Items.Add(new Branch() { Title = "Wilmington", Address = "355 Middlesex Avenue", Latitude = 42.566769, Longitude = -71.159566, Town = "Wilmington", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Church_Street%2C_Wilmington_MA.jpg/320px-Church_Street%2C_Wilmington_MA.jpg" });
            Items.Add(new Branch() { Title = "Worcester", Address = "611 Main Street", Latitude = 42.260149, Longitude = -71.804329, Town = "Worcester", ImagePath = "http://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Downtown_Worcester%2C_Massachusetts.jpg/640px-Downtown_Worcester%2C_Massachusetts.jpg" });
        }

        public System.Collections.ObjectModel.ObservableCollection<Branch> Items { get; set; }
    }
}