//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMV.Awesome.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchHistory
    {
        public System.Guid ID { get; set; }
        public string Town { get; set; }
        public double LicensingWait { get; set; }
        public double RegistrationWait { get; set; }
        public System.DateTimeOffset SampleTime { get; set; }
        public Nullable<System.DateTime> Fetched { get; set; }
    }
}
