// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using RMV.Awesome.Api.Models;

namespace RMV.Awesome.Api.Models
{
    public static partial class BranchCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Branch> DeserializeJson(JToken inputObject)
        {
            IList<Branch> deserializedObject = new List<Branch>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Branch branch = new Branch();
                branch.DeserializeJson(iListValue);
                deserializedObject.Add(branch);
            }
            return deserializedObject;
        }
    }
}
