// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using RMV.Awesome.UWP;
using RMV.Awesome.UWP.Models;

namespace RMV.Awesome.UWP
{
    public static partial class BranchExtensions
    {
        /// <param name='operations'>
        /// Reference to the RMV.Awesome.UWP.IBranch.
        /// </param>
        public static IList<RMVBranch> GetBranchList(this IBranch operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IBranch)s).GetBranchListAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the RMV.Awesome.UWP.IBranch.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<RMVBranch>> GetBranchListAsync(this IBranch operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<RMV.Awesome.UWP.Models.RMVBranch>> result = await operations.GetBranchListWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the RMV.Awesome.UWP.IBranch.
        /// </param>
        /// <param name='lat'>
        /// Required.
        /// </param>
        /// <param name='lng'>
        /// Required.
        /// </param>
        public static IList<RMVBranch> GetBranchListDistance(this IBranch operations, double lat, double lng)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IBranch)s).GetBranchListDistanceAsync(lat, lng);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the RMV.Awesome.UWP.IBranch.
        /// </param>
        /// <param name='lat'>
        /// Required.
        /// </param>
        /// <param name='lng'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<RMVBranch>> GetBranchListDistanceAsync(this IBranch operations, double lat, double lng, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<RMV.Awesome.UWP.Models.RMVBranch>> result = await operations.GetBranchListDistanceWithOperationResponseAsync(lat, lng, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the RMV.Awesome.UWP.IBranch.
        /// </param>
        public static bool GetRefreshTimes(this IBranch operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IBranch)s).GetRefreshTimesAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the RMV.Awesome.UWP.IBranch.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<bool> GetRefreshTimesAsync(this IBranch operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<bool> result = await operations.GetRefreshTimesWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
