// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using RMV.Awesome.UWP.Models;

namespace RMV.Awesome.UWP.Models
{
    public static partial class RMVBranchCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<RMVBranch> DeserializeJson(JToken inputObject)
        {
            IList<RMVBranch> deserializedObject = new List<RMVBranch>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                RMVBranch rMVBranch = new RMVBranch();
                rMVBranch.DeserializeJson(iListValue);
                deserializedObject.Add(rMVBranch);
            }
            return deserializedObject;
        }
    }
}
